STOCK_INDUSTRY_MERGE = """
MERGE INTO STOCK_INDUSTRY t
USING (
    SELECT
        :INDUSTRY_CODE AS INDUSTRY_CODE,
        :LARGE_CLASS AS LARGE_CLASS,
        :MEDIUM_CLASS AS MEDIUM_CLASS,
        :SMALL_CLASS AS SMALL_CLASS
    FROM dual
) s
ON (t.INDUSTRY_CODE = s.INDUSTRY_CODE)
WHEN MATCHED THEN UPDATE SET
    t.LARGE_CLASS = s.LARGE_CLASS,
    t.MEDIUM_CLASS = s.MEDIUM_CLASS,
    t.SMALL_CLASS = s.SMALL_CLASS
WHEN NOT MATCHED THEN INSERT (
    INDUSTRY_CODE,
    LARGE_CLASS,
    MEDIUM_CLASS,
    SMALL_CLASS
) VALUES (
    s.INDUSTRY_CODE,
    s.LARGE_CLASS,
    s.MEDIUM_CLASS,
    s.SMALL_CLASS
)
"""

STOCK_MASTER_MERGE = """
MERGE INTO STOCK_MASTER t
USING (
    SELECT
        :TICKER AS TICKER,
        :STOCK_NAME AS STOCK_NAME,
        :MARKET_CODE AS MARKET_CODE,
        :ASSET_TYPE AS ASSET_TYPE,
        :INDUSTRY_CODE AS INDUSTRY_CODE,
        :IS_LISTED AS IS_LISTED,
        :UPDATED_AT AS UPDATED_AT
    FROM dual
) s
ON (t.TICKER = s.TICKER)
WHEN MATCHED THEN UPDATE SET
    t.STOCK_NAME = s.STOCK_NAME,
    t.MARKET_CODE = s.MARKET_CODE,
    t.ASSET_TYPE = s.ASSET_TYPE,
    t.INDUSTRY_CODE = s.INDUSTRY_CODE,
    t.IS_LISTED = s.IS_LISTED,
    t.UPDATED_AT = s.UPDATED_AT
WHEN NOT MATCHED THEN INSERT (
    TICKER,
    STOCK_NAME,
    MARKET_CODE,
    ASSET_TYPE,
    INDUSTRY_CODE,
    IS_LISTED,
    UPDATED_AT
) VALUES (
    s.TICKER,
    s.STOCK_NAME,
    s.MARKET_CODE,
    s.ASSET_TYPE,
    s.INDUSTRY_CODE,
    s.IS_LISTED,
    s.UPDATED_AT
)
"""

DAILY_PRICE_MERGE = """
MERGE INTO DAILY_PRICE t
USING (
    SELECT
        :TICKER AS TICKER,
        :PRICE_DATE AS PRICE_DATE,
        :OPEN_PRICE AS OPEN_PRICE,
        :HIGH_PRICE AS HIGH_PRICE,
        :LOW_PRICE AS LOW_PRICE,
        :CLOSE_PRICE AS CLOSE_PRICE,
        :ADJ_CLOSE AS ADJ_CLOSE,
        :VOLUME AS VOLUME,
        :MARKET_CAP AS MARKET_CAP
    FROM dual
) s
ON (t.TICKER = s.TICKER AND t.PRICE_DATE = s.PRICE_DATE)
WHEN MATCHED THEN UPDATE SET
    t.OPEN_PRICE = s.OPEN_PRICE,
    t.HIGH_PRICE = s.HIGH_PRICE,
    t.LOW_PRICE = s.LOW_PRICE,
    t.CLOSE_PRICE = s.CLOSE_PRICE,
    t.ADJ_CLOSE = s.ADJ_CLOSE,
    t.VOLUME = s.VOLUME,
    t.MARKET_CAP = s.MARKET_CAP
WHEN NOT MATCHED THEN INSERT (
    TICKER,
    PRICE_DATE,
    OPEN_PRICE,
    HIGH_PRICE,
    LOW_PRICE,
    CLOSE_PRICE,
    ADJ_CLOSE,
    VOLUME,
    MARKET_CAP
) VALUES (
    s.TICKER,
    s.PRICE_DATE,
    s.OPEN_PRICE,
    s.HIGH_PRICE,
    s.LOW_PRICE,
    s.CLOSE_PRICE,
    s.ADJ_CLOSE,
    s.VOLUME,
    s.MARKET_CAP
)
"""

STOCK_DIVIDEND_MERGE = """
MERGE INTO STOCK_DIVIDEND t
USING (
    SELECT
        :TICKER AS TICKER,
        :EX_DIVIDEND_DATE AS EX_DIVIDEND_DATE,
        :DIVIDEND_PER_SHARE AS DIVIDEND_PER_SHARE,
        :RECORD_DATE AS RECORD_DATE,
        :PAYMENT_DATE AS PAYMENT_DATE,
        :DIVIDEND_TYPE AS DIVIDEND_TYPE
    FROM dual
) s
ON (t.TICKER = s.TICKER AND t.EX_DIVIDEND_DATE = s.EX_DIVIDEND_DATE)
WHEN MATCHED THEN UPDATE SET
    t.DIVIDEND_PER_SHARE = s.DIVIDEND_PER_SHARE,
    t.RECORD_DATE = s.RECORD_DATE,
    t.PAYMENT_DATE = s.PAYMENT_DATE,
    t.DIVIDEND_TYPE = s.DIVIDEND_TYPE
WHEN NOT MATCHED THEN INSERT (
    TICKER,
    EX_DIVIDEND_DATE,
    DIVIDEND_PER_SHARE,
    RECORD_DATE,
    PAYMENT_DATE,
    DIVIDEND_TYPE
) VALUES (
    s.TICKER,
    s.EX_DIVIDEND_DATE,
    s.DIVIDEND_PER_SHARE,
    s.RECORD_DATE,
    s.PAYMENT_DATE,
    s.DIVIDEND_TYPE
)
"""
